hyrodactil/accounts/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(
        r'^register/$',
        views.RegistrationView.as_view(),
        name='register'
    ),
    url(
        r'^confirmation/$',
        views.RegistrationConfirmationView.as_view(),
        name='register_confirmation'
    ),
    url(
        r'^activate/(?P<activation_key>\w+)/$',
        views.ActivateView.as_view(),
        name='activate'
    ),
    url(
        r'^promote/(?P<user_pk>\w+)/$',
        views.PromoteView.as_view(),
        name='promote'
    ),
    url(
        r'^delete/(?P<user_pk>\w+)/$',
        views.DeleteView.as_view(),
        name='delete'
    ),
    url(
        r'^details/$',
        views.ChangeDetailsView.as_view(),
        name='change_details'
    )
)

hyrodactil/hyrodactil/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'',
        include(
            'accounts.auth_urls',
            namespace='auth',
            app_name='accounts'
        )
    ),
    url(
        r'^accounts/',
        include(
            'accounts.urls',
            namespace='accounts',
            app_name='accounts'
        )
    ),
    url(
        r'^companies/',
        include(
            'companies.urls',
            namespace='companies',
            app_name='companies'
        )
    ),
    url(
        r'^settings/',
        include(
            'companysettings.urls',
            namespace='companysettings',
            app_name='companysettings'
        )
    ),
    url(
        r'^openings/',
        include(
            'openings.urls',
            namespace='openings',
            app_name='openings')
    ),
    url(
        r'^applications/',
        include(
            'applications.urls',
            namespace='applications',
            app_name='applications')
    ),
    url(
        r'^emails/',
        include(
            'customisable_emails.urls',
            namespace='customisable_emails',
            app_name='customisable_emails'
        )
    ),
    url(
        r'^',
        include(
            'dashboard.urls',
            namespace='dashboard',
            app_name='dashboard')
    ),
    url(
        r'^',
        include(
            'public.urls',
            namespace='public',
            app_name='public')
    )

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

hyrodactil/accounts/models.py
import datetime
import hashlib
import random
import string

from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager, PermissionsMixin
)

from django.db import models
from django.core import mail
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel

from companies.models import Company


class CustomUserManager(BaseUserManager):
    """
    Manager for the custom user, responsible for creating new users and
    activating them
    """
    def create_user(self, email, name, password=None, active=True, company=None,
                    is_company_admin=False, invited=False):
        """
        Creates a basic user which is active by default.
        If we want to create an inactive one, an activation key is generated
        """
        if not email:
            msg = _('Email is mandatory')
            raise ValueError(msg)

        # We don't want to activate invited users straight away
        if settings.SKIP_ACTIVATION and not invited:
            active = True

        user = self.model(
            email=CustomUserManager.normalize_email(email),
            name=name,
            is_company_admin=is_company_admin,
            company=company
        )
        user.set_password(password)

        if not active:
            # create token here
            user.activation_key = self._create_activation_token(email)
            user.is_active = False
            user.send_activation_email()

        user.save(using=self._db)

        return user

    def create_superuser(self, email, password, name):
        """
        Creates an active superuser.
        Superuser are active from the start, they don't receive an activation
        mail
        """
        user = self.create_user(email, name, password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user

    def activate_user(self, activation_key):
        """
        Activates an user account by its activation key.
        If the activation key doesn't exist (someone typed a random one or
        the user has already been activated), return False.
        Otherwise, return the updated user object.
        """
        if not activation_key:
            return False
        try:
            user = self.get(activation_key=activation_key)
        except self.model.DoesNotExist:
            return False

        if not user.activation_key_expired():
            user.activation_key = ''
            user.is_active = True
            user.save()
            return user

        return False

    def delete_expired_users(self):
        """
        Deletes all users that have an expired activation token
        """
        for user in self.all():
            if user.activation_key_expired():
                user.delete()

    def _create_activation_token(self, email):
        """
        Generates an activation token based on a random salt + the user's email
        """
        salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
        return hashlib.sha1(salt + email).hexdigest()


def get_file_path(instance, filename):
    """
    Used by the avatar field in the CustomUser model
    Base64 the name of the file and returns the path where it should be
    saved to
    """
    possible_chars = (string.ascii_letters + string.digits)
    new_name = ''.join(random.choice(possible_chars) for _ in xrange(6))

    ext = filename.split('.')[-1]
    return 'avatars/%s.%s' % (new_name, ext)


class CustomUser(TimeStampedModel, AbstractBaseUser, PermissionsMixin):
    """
    Custom user using the django 1.5 customisable users.
    Uses email as username field and adds optional avatar, first name, last
    name and an activation key
    """
    email = models.EmailField(
        verbose_name=_('Email'),
        max_length=255,
        unique=True,
        db_index=True,
    )

    USERNAME_FIELD = 'email'

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    is_company_admin = models.BooleanField(default=True)

    avatar = models.ImageField(
        verbose_name=_('Avatar'),
        blank=True,
        upload_to=get_file_path
    )
    name = models.CharField(
        verbose_name=_('Your name'),
        max_length=255
    )
    activation_key = models.CharField(
        verbose_name=_('Activation key'),
        max_length=40,
        blank=True
    )
    company = models.ForeignKey(
        Company, related_name='employees', blank=True, null=True
    )

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'user'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.name

    def get_status(self):
        if self.is_active:
            return _("Active")
        elif self.activation_key:
            return _("Invited")
        else:
            return _("Disabled")

    def activation_key_expired(self):
        """
        Determines if the activation key is expired.
        This is known by checking if the current date is after the date
        the user created its account + the ACCOUNT_ACTIVATION_DAYS period
        defined in the settings
        """
        delta = datetime.timedelta(days=settings.ACCOUNT_ACTIVATION_DAYS)
        now = datetime.datetime.now()

        if now > self.created + delta:
            return True
        else:
            return False

    def send_activation_email(self):
        """
        Use this method to send an activation email to a new user or resend a
        new one if the user asks for it .
        It needs 2 templates : one for the subject line (1 line only) and one
        for the body.
        """
        context = {
            'activation_key': self.activation_key,
            'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
            'site_name': settings.DISPLAY_SITE_NAME,
            'site_url': settings.APP_SITE_URL
        }

        subject = render_to_string(
            'accounts/activation_email_subject.txt', context
        )
        subject = ''.join(subject.splitlines())
        body = render_to_string('accounts/activation_email_body.txt', context)

        mail.send_mail(
            subject, body, settings.DEFAULT_FROM_EMAIL, [self.email]
        )

    def get_avatar_url(self):
        if self.avatar:
            return self.avatar.url

        return settings.STATIC_URL + 'img/default_avatar.jpg'

    def __unicode__(self):
        return self.get_full_name()

hyrodactil/templates/account_base.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}

<html>
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

  <title>
    {% block title %}
    {% endblock title %}

    | Hizard
  </title>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1">

  {% block extrahead %}
  {% endblock %}

  <link rel="stylesheet" href="{% static "css/app.css" %}" />
</head>
<body class="no-push">

<div class="account-container">
  {% include 'core/_messages.html' with messages=messages %}

  {% block content %}
  {% endblock content %}
</div>

<script src="{% static "js/vendor/jquery.js" %}"></script>
<script src="{% static "js/foundation/foundation.js" %}"></script>
<script src="{% static "js/vendor/custom.modernizr.js" %}"></script>

<script>
  $(document).foundation();

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
</script>

</body>
</html>

hyrodactil/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}
{% load core_extra %}

<html>
<head>
  <meta charset="utf-8">
  <link rel="icon" href="{% static "img/favicon.ico" %}" type="image/x-icon"/>
  <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon"/>
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

  <title>
    {% block title %}
    {% endblock title %}

    | Hizard
  </title>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1">

  {% block extrahead %}
  {% endblock %}

  <link rel="stylesheet" href="{% static "css/app.css" %}" />
</head>
<body>

  <nav class="left-menu">
    <h3><img src="{% static "img/logo.png" %}"></h3>
    <a class="{% active request 'accounts:change_details' %}" href="{% url 'accounts:change_details' %}">
      <i class="icon-user icon-2x"></i>{{ user.name }}
    </a>
    <a class="{% active request 'dashboard:dashboard' %}" href="{% url 'dashboard:dashboard' %}">
      <i class="icon-home icon-2x"></i>{% trans 'Dashboard' %}
    </a>
    <a class="{% active request 'openings:list_openings' %}" href="{% url 'openings:list_openings' %}">
      <i class="icon-folder-close icon-2x"></i>{% trans 'Openings' %}
    </a>
    <a class="{% active request 'applications:list_applications' %}" href="{% url 'applications:list_applications' %}">
      <i class="icon-group icon-2x"></i>{% trans 'Applicants' %}
    </a>
    <a href="{{ opening_list_url }}" target="_blank">
      <i class="icon-share-alt icon-2x"></i>{% trans 'Career site' %}
    </a>
    <a class="{% active request 'companysettings:main' %}" href="{% url 'companysettings:main' %}">
      <i class="icon-cogs icon-2x"></i>{% trans 'Settings' %}
    </a>
    <a href="{% url 'auth:logout' %}">
      <i class="icon-off icon-2x"></i>{% trans 'Logout' %}
    </a>
  </nav>

  <nav class="top-menu">
    <i class="icon-reorder icon-2x open-left-menu"></i>
    <span class="username">{{ user.name }}</span>
  </nav>

  <div class="container">
    {% include 'core/_messages.html' with messages=messages %}
    {% block content %}
    {% endblock content %}
  </div>

  <script src="{% static "js/vendor/jquery.js" %}"></script>
  <script src="{% static "js/foundation/foundation.js" %}"></script>
  <script src="{% static "js/vendor/custom.modernizr.js" %}"></script>
  <script src="{% static "js/foundation/foundation.reveal.js" %}"></script>
  <script src="{% static "js/foundation/foundation.alerts.js" %}"></script>
  <script src="{% static "js/foundation/foundation.section.js" %}"></script>
  <script src="{% static "js/csrf.js" %}"></script>

  <script>
    $(document).foundation();

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41253554-1', 'hizard.com');
    ga('send', 'pageview');

    $(document).ready(function() {
      $('.open-left-menu').click(function() {
        var $menu = $('.left-menu');
        $('body').toggleClass('push-to-right');
        $menu.toggleClass('open');

        if ($menu.hasClass('open')) {
          $('.top-menu').addClass('remove-logo-top-menu');
          $('.container').addClass('restrict-width-container ');
        } else {
          $('.top-menu').removeClass('remove-logo-top-menu');
          $('.container').removeClass('restrict-width-container ');
        }
      });
    });

  </script>

  {% block extra-js %}
  {% endblock extra-js %}

</body>
</html>

hyrodactil/templates/base_jobs.html
<!DOCTYPE html>

{% load i18n %}
{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock title %} | Hizard.com</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Hizard">

  <link rel="stylesheet" href="{% static "css/jobs.css" %}" />
</head>

<body>

  <header class="row">
    <h1>
      {% if company.website %}
        <a href="{{ company.website }}" target="_blank">{{ company.name }}</a>
      {% else %}
        {{ company.name }}
      {% endif %}
    </h1>
  </header>

  <section class="row wrapper">
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </section>

  <div class="row">
    {% block apply-header %}
    {% endblock apply-header %}
  </div>

  <div class="row content">
    <section class="large-6 columns">
      {% block section %}
      {% endblock section %}
    </section>

    <aside class="large-6 columns">
      {% block aside %}
      {% endblock aside %}
    </aside>

  </div>


</body>

</html>

hyrodactil/templates/base_openings.html
<!DOCTYPE html>

{% load i18n %}
{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="stylesheet" href="{% static "css/normalize.css" %}" />
  <link rel="stylesheet" href="{% static "css/jobs.css" %}" />
</head>

<body>

  <header class="row">
    <h1 class="large-9 columns">{% block header %}{% endblock header %}</h1>
    <a href="#" class="large-3 columns">{% trans 'Back to our website' %}</a>
  </header>

  {% block apply-header %}
  {% endblock apply-header %}

  <div class="content row">
    <section class="large-6 columns">
      {% block section %}
      {% endblock section %}
    </section>

    <aside class="large-6 columns">
      {% block aside %}
      {% endblock aside %}
    </aside>

  </div>


</body>

</html>

hyrodactil/templates/landing_page.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}

<html>
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

  <title>
    Hizard | Applicant tracking system
  </title>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1">

  <link rel="stylesheet" href="{% static "css/normalize.css" %}" />
  <link rel="stylesheet" href="{% static "css/landing.css" %}" />
</head>
<body>

  <div class="section-top white row">
    <div class="large-4 columns">
      <img width="150" height="150" src="{% static "img/logo-black.png" %}"/>
    </div>

    <div class="large-8 columns navigation">
      <a class="nav-link" href="#features">{% trans 'Features' %}</a>
      <a class="button-custom sign-up" href="{% url 'accounts:register' %}">{% trans 'Sign up' %}</a>
      <a class="nav-link" href="{% url 'auth:login' %}">{% trans 'Login' %}</a>
    </div>
  </div>

  {% if messages %}
    <div class="section row">
      {% for message in messages %}
        <div class="alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <div class="section hero">
    <div class="row">
      <h1 class="hero-heading">
        {% trans 'Post jobs' %}. <br>
        {% trans 'Get applicants' %}. <br>
        {% trans 'Manage them' %}.
      </h1>
      <p class="hero-subhead">{% trans 'Never lose sight of the right persons' %}.</p>
    </div>
  </div>

  <div class="row">
    <h2>{% trans 'Put your email in the box below to know when it launches' %}</h2>

    <div class="row">
      <form action="{% url 'public:add-interest' %}" method="POST">
        {% csrf_token %}
          <input name="email" id="id_email" type="email" placeholder="Your email" />
          <input type="submit" value="Let me know when it's ready" class="button-custom" />
      </form>
    </div>

  </div>

  <div class="section">
    <a href="#features"></a>
    <div class="row">
      <h1 class="section-title">Involve your whole company in the hiring process</h1>
      <p class="section-subtitle">You are working as a team. Hire as a team.</p>
      <div class="row">
        <div class="large-6 columns">
          <h3>Discuss applicants<br></h3>
          <img src="images/image-placeholder.svg">
        </div>
        <div class="large-6 columns">
          <h3>Rate application</h3>
          <img src="images/image-placeholder.svg">
        </div>
      </div>
    </div>
  </div>

  <div class="section grey">
    <div class="row">
      <h1 class="section-title">Your own mobile-friendly career site</h1>
      <p class="section-subtitle">Apply from anywhere.</p>
      <div class="row">
        <div class="large-6 columns">
          <h3>From a computer</h3>
          <img src="images/image-placeholder.svg">
        </div>
        <div class="large-6 columns">
          <h3>From a phone</h3>
          <img src="images/image-placeholder.svg">
        </div>
      </div>
    </div>
  </div>

  <div class="section footer">
    <div class="row">
      <div class="large-6 columns">
        <div class="footer-text">Hizard</div>
      </div>
      <div class="large-6 columns right-text">
        <div class="footer-text">Contact us:</div>
        <a class="inline-block social-icon first" href="mailto:team@hizard.com?subject=Hello">
          <img src="{% static "img/landing-email.png" %}" width="30">
        </a>
        <a class="inline-block social-icon" href="http://www.twitter.com/hizardapp">
          <img src="{% static "img/landing-twitter.png" %}" width="30">
        </a>
      </div>
    </div>
  </div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41253554-1', 'hizard.com');
  ga('send', 'pageview');
</script>


</body>
</html>

hyrodactil/templates/new_base.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}
{% load core_extra %}

<html>
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

  <title>
    {% block title %}
    {% endblock title %}

    | Hizard
  </title>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1">

  {% block extrahead %}
  {% endblock %}

  <link rel="stylesheet" href="{% static "css/normalize.css" %}" />
  <link rel="stylesheet" href="{% static "css/new.css" %}" />
</head>
<body>

  <nav class="left-menu">
    <h3><img src="{% static "img/logo.png" %}"></h3>
    <a class="{% active request 'accounts:change_details' %}" href="{% url 'accounts:change_details' %}">
      <i class="icon-user icon-2x"></i>{{ user.name }}
    </a>
    <a class="{% active request 'dashboard:dashboard' %}" href="{% url 'dashboard:dashboard' %}">
      <i class="icon-home icon-2x"></i>{% trans 'Dashboard' %}
    </a>
    <a class="{% active request 'openings:list_openings' %}" href="{% url 'openings:list_openings' %}">
      <i class="icon-folder-close icon-2x"></i>{% trans 'Openings' %}
    </a>
    <a class="{% active request 'applications:list_applications' %}" href="{% url 'applications:list_applications' %}">
      <i class="icon-group icon-2x"></i>{% trans 'Applicants' %}
    </a>
    <a href="{{ opening_list_url }}" target="_blank">
      <i class="icon-share-alt icon-2x"></i>{% trans 'Career site' %}
    </a>
    <a class="{% active request 'companysettings:main' %}" href="{% url 'companysettings:main' %}">
      <i class="icon-cogs icon-2x"></i>{% trans 'Settings' %}
    </a>
  </nav>

  <nav class="top-menu">
    <i class="icon-reorder icon-2x open-left-menu"></i>
    <span class="username">{{ user.name }}</span>
  </nav>

  <div class="container">
    {% include 'core/_messages.html' with messages=messages %}
    {% block content %}
    {% endblock content %}
  </div>

  <script src="{% static "js/vendor/jquery.js" %}"></script>
  <script src="{% static "js/foundation/foundation.js" %}"></script>
  <script src="{% static "js/vendor/custom.modernizr.js" %}"></script>
  <script src="{% static "js/foundation/foundation.reveal.js" %}"></script>
  <script src="{% static "js/foundation/foundation.alerts.js" %}"></script>
  <script src="{% static "js/foundation/foundation.section.js" %}"></script>
  <script src="{% static "js/csrf.js" %}"></script>

  <script>
    $(document).foundation();

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41253554-1', 'hizard.com');
    ga('send', 'pageview');

    $(document).ready(function() {
      $('.open-left-menu').click(function() {
        var $menu = $('.left-menu');
        $('body').toggleClass('push-to-right');
        $menu.toggleClass('open');

        if ($menu.hasClass('open')) {
          $('.top-menu').addClass('remove-logo-top-menu');
          $('.container').addClass('restrict-width-container ');
        } else {
          $('.top-menu').removeClass('remove-logo-top-menu');
          $('.container').removeClass('restrict-width-container ');
        }
      });
    });

  </script>

  {% block extra-js %}
  {% endblock extra-js %}

</body>
</html>