hyrodactil/accounts/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(
        r'^register/$',
        views.RegistrationView.as_view(),
        name='register'
    ),
    url(
        r'^confirmation/$',
        views.RegistrationConfirmationView.as_view(),
        name='register_confirmation'
    ),
    url(
        r'^activate/(?P<activation_key>\w+)/$',
        views.ActivateView.as_view(),
        name='activate'
    ),
    url(
        r'^promote/(?P<user_pk>\w+)/$',
        views.PromoteView.as_view(),
        name='promote'
    ),
    url(
        r'^delete/(?P<user_pk>\w+)/$',
        views.DeleteView.as_view(),
        name='delete'
    ),
    url(
        r'^details/$',
        views.ChangeDetailsView.as_view(),
        name='change_details'
    )
)

hyrodactil/applications/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
   url(
       r'^$',
       views.ApplicationListView.as_view(),
       name='list_applications'
   ),
   url(
       r'^list/(?P<pk>\d+)/$',
       views.ApplicationListView.as_view(),
       name='list_applications_opening'
   ),
   url(
        r'^(?P<pk>\d+)/$',
        views.ApplicationDetailView.as_view(),
        name='application_detail'
   ),
   url(
        r'^(?P<application_id>\d+)/create_message/$',
        views.ApplicationMessageCreateView.as_view(),
        name='create_message'
   ),
   url(
        r'^add/(?P<opening_id>\d+)/$',
        views.ManualApplicationView.as_view(),
        name='manual_application'
   ),
   url(
       r'^rate/(?P<application_id>\d+)/(?P<rating>-?\d+)$',
       views.RateView.as_view(),
       name='rate'
   )
)

hyrodactil/hyrodactil/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'',
        include(
            'accounts.auth_urls',
            namespace='auth',
            app_name='accounts'
        )
    ),
    url(
        r'^accounts/',
        include(
            'accounts.urls',
            namespace='accounts',
            app_name='accounts'
        )
    ),
    url(
        r'^companies/',
        include(
            'companies.urls',
            namespace='companies',
            app_name='companies'
        )
    ),
    url(
        r'^settings/',
        include(
            'companysettings.urls',
            namespace='companysettings',
            app_name='companysettings'
        )
    ),
    url(
        r'^openings/',
        include(
            'openings.urls',
            namespace='openings',
            app_name='openings')
    ),
    url(
        r'^applications/',
        include(
            'applications.urls',
            namespace='applications',
            app_name='applications')
    ),
    url(
        r'^emails/',
        include(
            'customisable_emails.urls',
            namespace='customisable_emails',
            app_name='customisable_emails'
        )
    ),
    url(
        r'^',
        include(
            'dashboard.urls',
            namespace='dashboard',
            app_name='dashboard')
    ),
    url(
        r'^',
        include(
            'public.urls',
            namespace='public',
            app_name='public')
    )

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

hyrodactil/openings/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(
        r'^$',
        views.OpeningListView.as_view(),
        name='list_openings'
    ),
    url(
        r'^new/$',
        views.OpeningCreateView.as_view(),
        name='create_opening'
    ),
    url(
        r'^(?P<pk>\d+)/edit/$',
        views.OpeningUpdateView.as_view(),
        name='update_opening'
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        views.OpeningDeleteView.as_view(),
        name='delete_opening'
    ),
    url(
        r'^(?P<pk>\d+)/',
        views.OpeningDetailView.as_view(),
        name='detail_opening'
    ),
    url(
        r'^publish/(?P<pk>\d+)/',
        views.OpeningPublishView.as_view(),
        name='publish_opening'
    )
)

hyrodactil/openings/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_countries import CountryField
from model_utils import Choices
from model_utils.models import TimeStampedModel

from companies.models import Company
from companysettings.models import InterviewStage


class Opening(TimeStampedModel):
    EMPLOYMENT_TYPES = Choices(
        ('part_time', _('Part Time')),
        ('full_time', _('Full Time')),
        ('internship', _('Internship')),
    )

    title = models.CharField(max_length=770)
    description = models.TextField()
    is_private = models.BooleanField(default=False)
    department = models.CharField(_("Department"), max_length=128, blank=True)
    country = CountryField(_("Country"), blank=True)
    city = models.CharField(_("City"), max_length=128, blank=True)
    published_date = models.DateTimeField(blank=True, null=True)
    employment_type = models.CharField(
        choices=EMPLOYMENT_TYPES,
        default=EMPLOYMENT_TYPES.full_time,
        max_length=20
    )

    company = models.ForeignKey(Company)

    def stage_counts(self):
        for stage in InterviewStage.objects.filter(company=self.company):
            yield self.application_set.filter(current_stage=stage).count()

    def get_apply_url(self):
        company_prefix = (
            settings.COMPANY_URL_PREFIX % self.company.subdomain
        )
        return "%s%s" % (
            company_prefix, reverse('public:apply', args=(self.id,))
        )

    def get_location_string(self):
        location = ''

        if self.city:
            location += '%s' % self.city
            if self.country:
                location += ', '

        if self.country:
            location += '%s' % unicode(self.country.name)
        return location

    def get_status(self):
        if self.is_private:
            return _('Private')

        if self.published_date:
            return _('Published')

        return _('Created')

    def __str__(self):
        return '%s' % self.title


class OpeningQuestion(TimeStampedModel):
    title = models.CharField(max_length=770)
    opening = models.ForeignKey(Opening, related_name='questions')
    position = models.IntegerField()

    class Meta:
        ordering = ['position']

    def __str__(self):
        return '%s' % self.title

hyrodactil/openings/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Opening


class OpeningForm(forms.ModelForm):
    class Meta:
        model = Opening
        fields = ('title', 'description', 'employment_type', 'is_private',
                  'department', 'country', 'city',)

    def __init__(self, company, *args, **kwargs):
        super(OpeningForm, self).__init__(*args, **kwargs)
        self.company = company

        if self.instance:
            self.questions = self.instance.questions.all()

        self.fields['is_private'].label = _("Private opening")

    def _clean_questions(self):
        self.questions_present = {}
        for field in self.data:
            if field.startswith('question') and self.data[field]:
                prefix, question_id = field.split("-")
                position = self.data['position-question-%s' % question_id]
                self.questions_present[field] = (position, self.data[field])

    def clean(self):
        self._clean_questions()
        return super(OpeningForm, self).clean()

    def save(self, *args, **kwargs):
        self.instance.company = self.company

        opening = super(OpeningForm, self).save(*args, **kwargs)

        if self.instance:
            for question in self.questions:
                field_name = 'question-' + str(question.id)
                if field_name not in self.questions_present:
                    question.delete()
                else:
                    present_position, present_title =\
                            self.questions_present[field_name]
                    if (question.title != present_title or
                        question.position != question.position):
                        question.position = present_position
                        question.title = present_title
                        question.save()
                    del self.questions_present[field_name]

            for field in self.questions_present:
                present_position, present_title = self.questions_present[field]
                opening.questions.create(title=present_title,
                                         position=present_position)

        return opening

hyrodactil/openings/views.py
from datetime import datetime

from braces.views import LoginRequiredMixin
from django.db.models import Count

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, View


from .forms import OpeningForm
from .models import Opening
from core.views import MessageMixin, QuickDeleteView, RestrictedUpdateView
from core.views import RestrictedDetailView, RestrictedListView


class OpeningListView(LoginRequiredMixin,  RestrictedListView):
    model = Opening

    def get_queryset(self):
        query_set = super(OpeningListView, self).get_queryset()
        query_set = query_set.annotate(number_applications=Count('application'))
        return query_set


class OpeningCreateView(LoginRequiredMixin, MessageMixin, CreateView):
    model = Opening
    form_class = OpeningForm
    action = 'created'
    success_message = _('Opening created.')

    def get_form(self, form_class):
        return form_class(self.request.user.company, **self.get_form_kwargs())

    def get_success_url(self):
        return reverse('openings:detail_opening', args=(self.object.id,))


class OpeningUpdateView(
    LoginRequiredMixin, MessageMixin, RestrictedUpdateView
):
    model = Opening
    form_class = OpeningForm
    action = 'updated'
    success_message = _('Opening updated.')

    def get_form(self, form_class):
        return form_class(self.request.user.company, **self.get_form_kwargs())

    def get_success_url(self):
        return reverse('openings:detail_opening', args=(self.object.id,))


class OpeningDeleteView(LoginRequiredMixin, QuickDeleteView):
    model = Opening
    success_url = reverse_lazy('openings:list_openings')
    success_message = _('Opening deleted.')


class OpeningDetailView(LoginRequiredMixin, RestrictedDetailView):
    model = Opening


class OpeningPublishView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        opening = get_object_or_404(Opening, id=self.kwargs['pk'])

        if opening.company != self.request.user.company:
            raise Http404

        if opening.published_date:
            opening.published_date = None
            opening.save()
            messages.success(request, _('Opening unpublished.'))
        else:
            opening.published_date = datetime.now()
            opening.save()
            messages.success(request, _('Opening published.'))

        return redirect(reverse('openings:detail_opening', args=(self.kwargs['pk'],)))

hyrodactil/templates/openings/opening_detail.html
{% extends "base.html" %}

{% load i18n %}


{% block title %}
  {{ opening.title }}
{% endblock title %}


{% block content %}

  <h1>{{ opening.title }}</h1>


  <div class="large-7 columns">
    <p>
      {{ opening.get_employment_type_display }}
      <br>

      {% if opening.get_location_string %}
        {{ opening.get_location_string }}
        <br>
      {% endif %}

      {% if opening.is_private %}
        {% trans 'Private opening' %}
      {% else %}
        {% trans 'Public opening' %}
      {% endif %}
      <br>

      {% if opening.published_date %}
        {% trans 'Published' %}
      {% else %}
        {% trans 'Unpublished' %}
      {% endif %}

      <h3>{% trans 'Description' %}</h3>
      {{ opening.description|safe }}
    </p>
  </div>

  <div class="large-5 columns">

    <div class="box large-8 columns large-centered box-with-icon">
      <div class="box-header">
        <h2>{% trans 'Actions' %}</h2>
      </div>

      <ul class="styled-list">
        <li>
          <a href="{% url 'openings:update_opening' opening.pk %}"><i class="icon-edit"></i>{% trans 'Edit this opening' %}</a>
        </li>
        {% comment %} Commented by Gautier on 3/11/2013 as I think we should only soft-delete things
        <li>
          <a href="{% url 'openings:delete_opening' opening.pk %}"><i class="icon-trash"></i>{% trans 'Delete this opening' %}</a>
        </li>
        {% endcomment %}
        <li>
          <a href="{% url 'applications:manual_application' opening.pk %}"><i class="icon-upload"></i>{% trans 'Add applicant' %}</a>
        </li>
        <li>
          <a href="{% url 'openings:publish_opening' opening.pk %}">
            {% if not opening.published_date %}
              <i class="icon-ok-circle"></i>{% trans 'Publish this opening' %}
            {% else %}
              <i class="icon-remove-circle"></i>{% trans 'Unpublish this opening' %}
            {% endif %}
          </a>
        </li>
    </div>

    <div class="box large-8 columns large-centered link-box box-with-icon">
      <div class="box-header">
        <h2>{% trans 'Links' %}</h2>
      </div>

      <ul class="styled-list">
        <li>
          <a href="{% url "applications:list_applications_opening" opening.id %}"><i class="icon-external-link"></i>{% trans 'Applicants list' %}</a>
        </li>
        {% if opening.published_date %}
          <li>
            <a href=" {{ opening.get_apply_url }}" target="_blank"><i class="icon-external-link-sign"></i>{% trans 'Job link' %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>

{% endblock content %}

hyrodactil/templates/openings/opening_form.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}


{% block title %}
  {% if opening %}
    {% trans 'Edit' %} {{ opening.title }}
  {% else %}
    {% trans 'Add an opening' %}
  {% endif %}
{% endblock title %}


{% block content %}

  <h1>
    {% if opening %}
      {% blocktrans with title=opening.title %}
        Edit {{ title }} opening
      {% endblocktrans %}
    {% else %}
      {% trans 'Add an opening' %}
    {% endif %}
  </h1>

  <form action="." method="POST" id="opening-form">
    {% csrf_token %}

    {% if form.non_field_errors %}
      <small class="error">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </small>
    {% endif %}

    {% for field in form.hidden_fields %}
      {{ field }}
    {% endfor %}

    <div class="large-6 columns">
      {% include 'core/_field.html' with field=form.title %}
      {% include 'core/_field.html' with field=form.description %}
      {% include 'core/_field.html' with field=form.employment_type %}
    </div>

    <div class="large-6 columns">
      {% include 'core/_field.html' with field=form.department %}
      {% include 'core/_field.html' with field=form.is_private %}
      {% include 'core/_field.html' with field=form.country %}
      {% include 'core/_field.html' with field=form.city %}
      {% include 'core/_field.html' with field=form.loc_postcode %}

      <div class="questions large-12 columns">
        <h4>{% trans 'Questions' %}</h4>

        {% for question in form.questions %}
          <div class="question large-12 columns">
            <div class="large-1 columns remove-question"><i class="icon-trash icon-large"></i></div>
            <div class="large-11 columns">
              <input type="text"  name="question-{{ question.id }}" value="{{ question.title }}"/>
              <input type="hidden"  name="position-question-{{ question.id }}" value="{{ question.position }}"/>
            </div>
          </div>
        {% endfor %}
      </div>
      <a class="button add-question" href="#">{% trans 'Add a question' %}</a>
    </div>

    <div class="large-12 columns">
      {% if opening %}
        <input type="submit" class="button" value="{% trans 'Save changes' %}" />
      {% else %}
        <input type="submit" class="button" value="{% trans 'Create this opening' %}" />
      {% endif %}
    </div>

  </form>

  <div class="question large-12 columns" id="question-template" style="display: none;">
    <div class="large-1 columns remove-question"><i class="icon-trash icon-large"></i></div>
    <div class="large-11 columns">
      <input type="text" name="question-name" value=""/>
      <input type="hidden" name="question-position" value=""/>
    </div>
  </div>

{% endblock content %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static "css/select2.css" %}" />
{% endblock %}                                                                  
                                                                                
{% block extra-js %}
  <script src="{% static "js/select2.js" %}"></script>
  <script src="{% static "js/vendor/tinymce/tinymce.min.js" %}"></script>
  <script src="{% static "js/vendor/tinymce/jquery.tinymce.min.js" %}"></script>
  <script>
    $(document).ready(function() {

      $('textarea').tinymce({
        plugins: "link image preview fullscreen hr",
        toolbar: "undo redo | bold italic |  hr  | bullist numlist | link unlink | preview",
        menubar: false,
        statusbar: false,
        height: 200
      });

      $('input[id$="included"]').click(function() {
          var $required = $(this).parent().siblings().find('input[id$="required"]');

          if ($(this).is(':checked')) {
            $required.removeAttr("disabled");
          } else {
            $required.prop('checked', false);
            $required.attr("disabled", true);
          }
      });

      $("#id_country").select2({width: '50%'})
      var options = $.map($("#id_department option"), function (el) {
        return el.text;
      });

      function highestQuestionPosition () {
        var max = 1;
        $("form#opening-form input[type=hidden]").each(function (index, val) {
          var input_name = $(val).attr("name");
          if (/^position-question-/.test(input_name)) {
            var position = + $(val).val();
            if (position > max) {
              max = position;
            }
          }
        });
        return max;
      }

      $('.add-question').click(function(e) {
        e.preventDefault();
        var rand = Math.random().toString(36).substring(7),
            $input = $("#question-template").clone(),
            $questionName = $input.find("input[name=question-name]"),
            $questionPosition = $input.find("input[name=question-position]");
        $input.attr("id", "");

        $questionName.attr("name", 'question-' + rand);
        $questionPosition.attr("name", 'position-question-' + rand);

        $questionPosition.val(highestQuestionPosition() + 1);

        $input.show();
        $('.questions').append($input);
        $input.focus();
      });

      $('body').on("click", ".remove-question", function(e){
        $(this).parents('.question').remove();
      });

    });
  </script>
{% endblock %}

hyrodactil/templates/openings/opening_list.html
{% extends "base.html" %}

{% load i18n %}


{% block title %}
  {% trans 'Openings' %}
{% endblock title %}


{% block content %}

  <h1>{% trans 'Openings' %}</h1>

  <span class="actions">
    <a href="{% url 'openings:create_opening' %}" class="button">
      {% trans "Create an opening" %}
    </a>
    <a href="#" class="button"
       data-reveal-id="add-applicant-modal">
      {% trans "Add a candidate" %}
    </a>
  </span>


  <div class="box">
    <div class="box-header">
      <h2>{% trans 'Active openings' %}</h2>
    </div>

    <ul class="styled-list">
      {% for opening in opening_list %}
        <li>
          <span class="large-5 columns">
            <a href="{% url 'openings:detail_opening' opening.id %}">{{ opening.title }}</a>
            <br>
            {% if opening.get_location_string %}
              {{ opening.get_location_string  }}
            {% endif %}
          </span>

          <span class="large-3 columns">
            <a href="{% url 'applications:list_applications_opening' opening.id %}">{{ opening.number_applications }} {% trans ' applicants' %}</a>
          </span>

          <span class="large-4 columns">
            {{ opening.get_status }} {% if opening.published_date %} : {{ opening.published_date }}{% endif %}
          </span>
        </li>
      {% endfor %}
    </ul>
  </div>

  <div id="add-applicant-modal" class="reveal-modal">
    <h3>{% trans 'Add applicant' %}</h3>

    <div class="row">
      <p class="large-12 column">
      {% blocktrans %}
      Add an applicant for the following opening :
      {% endblocktrans %}
      </p>
    </div>

    <div class="row">
      <div class="large-9 column">
        <select id="opening-list">
          {% for opening in opening_list %}
            <option value="{% url 'applications:manual_application' opening.pk %}">{{ opening.title }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="large-3 column">
        <button class="button right" id="add-applicant">{% trans 'Add applicant' %}</button>
      </div>

    <a class="close-reveal-modal">&#215;</a>
  </div>

{% endblock content %}

{% block extra-js %}
  <script type="text/javascript">
   $('button#add-applicant').click(function() {
       window.location.href = $("select#opening-list option:selected").attr("value");
   });
  </script>
{% endblock extra-js %}