hyrodactil/accounts/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(
        r'^register/$',
        views.RegistrationView.as_view(),
        name='register'
    ),
    url(
        r'^confirmation/$',
        views.RegistrationConfirmationView.as_view(),
        name='register_confirmation'
    ),
    url(
        r'^activate/(?P<activation_key>\w+)/$',
        views.ActivateView.as_view(),
        name='activate'
    ),
    url(
        r'^promote/(?P<user_pk>\w+)/$',
        views.PromoteView.as_view(),
        name='promote'
    ),
    url(
        r'^delete/(?P<user_pk>\w+)/$',
        views.DeleteView.as_view(),
        name='delete'
    ),
    url(
        r'^details/$',
        views.ChangeDetailsView.as_view(),
        name='change_details'
    )
)

hyrodactil/companysettings/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

   url(
       r'^$',
       views.SettingsView.as_view(),
       name='main'
   ),
    url(
        r'^stages/$',
        views.InterviewStageListView.as_view(),
        name='list_stages'
    ),
    url(
        r'^stage/$',
        views.InterviewStageCreateUpdateView.as_view(),
        name='ajax_stage'
    ),
    url(
        r'^stage/(?P<pk>\d+)/delete/$',
        views.InterviewStageDeleteView.as_view(),
        name='delete_stage'
    ),
    url(
        r'^stage/(?P<pk>\d+)/reorder/(?P<delta>-1|1)/$',
        views.InterviewStageReorderView.as_view(),
        name='reorder_stage'
    ),
    url(
        r'^information/$',
        views.UpdateCompanyInformationView.as_view(),
        name='update_information'
    ),
    url(
        r'^widget/$',
        views.WidgetView.as_view(),
        name='widget'
    ),

)

hyrodactil/hyrodactil/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'',
        include(
            'accounts.auth_urls',
            namespace='auth',
            app_name='accounts'
        )
    ),
    url(
        r'^accounts/',
        include(
            'accounts.urls',
            namespace='accounts',
            app_name='accounts'
        )
    ),
    url(
        r'^companies/',
        include(
            'companies.urls',
            namespace='companies',
            app_name='companies'
        )
    ),
    url(
        r'^settings/',
        include(
            'companysettings.urls',
            namespace='companysettings',
            app_name='companysettings'
        )
    ),
    url(
        r'^openings/',
        include(
            'openings.urls',
            namespace='openings',
            app_name='openings')
    ),
    url(
        r'^applications/',
        include(
            'applications.urls',
            namespace='applications',
            app_name='applications')
    ),
    url(
        r'^emails/',
        include(
            'customisable_emails.urls',
            namespace='customisable_emails',
            app_name='customisable_emails'
        )
    ),
    url(
        r'^',
        include(
            'dashboard.urls',
            namespace='dashboard',
            app_name='dashboard')
    ),
    url(
        r'^',
        include(
            'public.urls',
            namespace='public',
            app_name='public')
    )

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

hyrodactil/companysettings/models.py
from django.db import models

from model_utils.models import TimeStampedModel
from companies.models import Company


class InterviewStage(TimeStampedModel):
    name = models.CharField(max_length=100)
    position = models.IntegerField(null=True)
    tag = models.CharField(blank=True, max_length=15)

    company = models.ForeignKey(Company, null=True)

    class Meta:
        ordering = ['position']

    def __unicode__(self):
        return self.name

    def change_position(self, delta):
        delta = int(delta)
        if self.position == 1 and delta == -1:
            return

        try:
            other_stage = InterviewStage.objects.get(
                company=self.company,
                position=self.position + delta
            )
        except InterviewStage.DoesNotExist:
            # Should not happen
            return

        other_stage.position = self.position
        other_stage.save()
        self.position = self.position + delta
        self.save()

    def prepare_for_deletion(self):
        stages_to_modify = InterviewStage.objects.filter(
            company=self.company, position__gt=self.position
        )

        for stage in stages_to_modify:
            stage.position -= 1
            stage.save()

hyrodactil/companysettings/forms.py
from django import forms
from companies.models import Company

from .models import InterviewStage
from accounts.models import CustomUser


class InterviewStageForm(forms.ModelForm):
    class Meta:
        model = InterviewStage
        fields = ('name',)


class CustomUserInviteForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email',)

    def save(self, commit=True, company=None, is_company_admin=False):
        """
        Save the user using the manager to make sure it creates the
        activation token and sens the activation email
        """
        email = self.cleaned_data["email"]

        if commit:
            user = CustomUser.objects.create_user(
                email=email,
                name='Invited User',
                password=None,
                active=False,
                is_company_admin=is_company_admin,
                company=company,
                invited=True
            )
            return user


class CompanyInformationForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'website', 'description')

hyrodactil/companysettings/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Max
from django.http import HttpResponseRedirect, Http404
from django.views.generic import CreateView, TemplateView, View
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _

from braces.views import LoginRequiredMixin, JSONResponseMixin, AjaxResponseMixin

from .forms import (
    InterviewStageForm, CompanyInformationForm
)
from .forms import CustomUserInviteForm
from .models import InterviewStage
from companies.models import Company
from accounts.models import CustomUser
from core.views import MessageMixin, QuickDeleteView, RestrictedUpdateView


class CreateUpdateAjaxView(
    LoginRequiredMixin, JSONResponseMixin, AjaxResponseMixin, View
):
    def post_ajax(self, request, *args, **kwargs):
        data = request.POST.copy()

        if 'id' in data:
            obj_to_update = self.model.objects.filter(id=int(data['id']))
            if obj_to_update:
                form = self.form(data, instance=obj_to_update[0])
            else:
                return self.render_json_response({
                    'result': 'error',
                    'message': unicode(self.message_not_exist)
                })
        else:
            form = self.form(data)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.company = self.request.user.company
            position_max = obj.company.interviewstage_set.aggregate(Max('position'))['position__max'] or 0
            obj.position = position_max + 1

            obj.save()
            return self.render_json_response({
                'result': 'success',
                'id': obj.id,
                'message': unicode(self.message_success)
            })
        else:
            return self.render_json_response({
                'result': 'error',
                'errors': form.errors,
                'message': unicode(self.message_errors)
            })


class InterviewStageListView(LoginRequiredMixin, TemplateView):
    model = InterviewStage
    template_name = 'companysettings/interviewstage_list.html'

    def get_context_data(self, **kwargs):
        context = super(InterviewStageListView, self).get_context_data(**kwargs)
        stages = InterviewStage.objects.filter(
            company=self.request.user.company
        )
        custom_stages = [stage for stage in stages if stage.tag == '']
        context['stages'] = custom_stages

        return context


class InterviewStageCreateUpdateView(CreateUpdateAjaxView):
    model = InterviewStage
    form = InterviewStageForm
    message_success = _('Stage saved.')
    message_errors = _('Please correct the errors below.')
    message_not_exist = _('The stage does not exist.')


class InterviewStageDeleteView(LoginRequiredMixin, QuickDeleteView):
    model = InterviewStage
    success_url = reverse_lazy('companysettings:list_stages')
    success_message = _('Stage deleted.')

    def get(self, *args, **kwargs):
        stage = self.get_object()
        if stage.company == self.request.user.company:
            stage.prepare_for_deletion()
            return super(InterviewStageDeleteView, self) .get(args, kwargs)

        raise Http404


class InterviewStageReorderView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        stage = InterviewStage.objects.get(
            id=kwargs.pop('pk'), company=self.request.user.company
        )
        delta = kwargs.pop('delta')
        stage.change_position(delta)
        messages.success(self.request, 'Stages reordered.')
        return HttpResponseRedirect(reverse('companysettings:list_stages'))


class SettingsView(LoginRequiredMixin, CreateView):
    template_name = "companysettings/customuser_list.html"
    model = CustomUser
    form_class = CustomUserInviteForm
    success_url = reverse_lazy('companysettings:main')

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        users = CustomUser.objects.filter(
            company=self.request.user.company
        )
        context['users'] = [user for user in users if user.is_active is True]
        context['invited_users'] = [user for user in users if user.is_active is False]
        return context

    def form_valid(self, form):
        form.save(company=self.request.user.company)
        return redirect(self.success_url)


class UpdateCompanyInformationView(
    LoginRequiredMixin, MessageMixin, RestrictedUpdateView
):
    model = Company
    form_class = CompanyInformationForm
    success_url = reverse_lazy('companysettings:update_information')
    success_message = _('Company information updated.')
    template_name = 'companysettings/information_form.html'

    def get_object(self):
        return self.request.user.company


class WidgetView(LoginRequiredMixin, TemplateView):
    template_name = 'companysettings/widget.html'

    def get_context_data(self, **kwargs):
        context = super(WidgetView, self).get_context_data(**kwargs)
        embed_url = '//%s.%s/embed.js' % (
            self.request.user.company.subdomain.lower(),
            'hizard.com'
        )
        snippet = """
<div id="hizard-openings"></div>\n
<script type="text/javascript">
    (function() {
      var hiz = document.createElement('script');
      hiz.type = 'text/javascript';
      hiz.async = true;
      hiz.src = '%s';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hiz);
    })();
</script>
        """ % embed_url
        context['snippet'] = snippet
        return context

hyrodactil/templates/companysettings/_dropdown_form.html
{% load i18n %}

<div id="{{ dropdown_id }}" class="f-dropdown small content" data-dropdown-content>

  <form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}

      <div class="row">
        <div class="large-12 columns {% if field.errors and error_object_id == object_id %} error {% endif %}">
          {{ field.label_tag }}
          {{ field }}

          {% if field.errors and error_object_id == object_id  %}
            <small class="rounded-error">
              {% for error in field.errors %}
                {{ error }}
              {% endfor %}
            </small>
          {% endif %}
        </div>
      </div>

    {% endfor %}


    <br>

    <div class="right">
      <input type="submit" class=" button-positive" value="{% trans 'Save' %}" />
    </div>

  </form>

</div>

hyrodactil/templates/companysettings/_modal_confirm.html
{% load i18n %}

<div id="delete-confirm-modal" class="reveal-modal">
  <h4>{% trans "Wait a second!" %}</h4>

  <div>
    <div class="large-12 columns">
      {% blocktrans %}
      <p>You are about to delete : <strong id="object-name"></strong></p>
      <p>Are you sure you want to do that?</p>
      {% endblocktrans %}
    </div>
  </div>

  <hr/>

  <div class="row">
    <a href="#" id="cancel-link"
      value="{% trans 'Cancel' %}"
      class="button columns push-7 large-2"
      >{% trans 'Cancel' %}</a>

    <a href="" id="confirm-delete-link"
      value="{% trans 'Delete' %}"
      class="button-alert columns large-2">{% trans 'Delete' %}</a>
  </div>

  <a class="close-reveal-modal">&#215;</a>
</div>

hyrodactil/templates/companysettings/customuser_list.html
{% extends "companysettings/main.html" %}

{% load i18n %}
{% load staticfiles %}


{% block title %}
  {% trans 'Manage users' %}
{% endblock title %}

{% block settings-content %}
  <div class="large-12 columns">
    <form action="." method="POST" class="large-6 columns">
      {% csrf_token %}

      {% for field in form %}
        {% include 'core/_field.html' with field=field %}
      {% endfor %}

      <div class="large-12 columns">
        <input type="submit" value="{% trans 'Invite user' %}" class="button" />
      </div>
    </form>
  </div>

  <div class="box large-5 columns left">
    <div class="box-header">
      <h2>{% trans 'Active users' %}</h2>
    </div>

    <ul class="styled-list">
      {% for user in users %}
        <li>
          <img src="{{ user.get_avatar_url }}" alt="Avatar" />
          <strong>{{ user.name }} {% if user.is_company_admin %}({% trans 'administrator' %}){% endif %}</strong>
          <br>
          <br>

          {% if request.user.is_company_admin and request.user != user %}
            <a class="button" href="{% url 'accounts:delete' user.id %}">{% trans 'Delete' %}</a>
            <a class="button" href="{% url 'accounts:promote' user.id %}">{% trans 'Make administrator' %}</a>
          {% endif %}

        </li>
      {% endfor %}
    </ul>
  </div>

  <div class="box large-5 columns right">
    <div class="box-header">
      <h2>{% trans 'Invited users' %}</h2>
    </div>

    <ul class="styled-list">
      {% for user in invited_users %}
        <li>
          <strong>{{ user.email }}</strong>
          <br>
          <br>
          {% trans 'Invited the ' %}{{ user.created|date:"SHORT_DATE_FORMAT" }}
        </li>
      {% endfor %}
    </ul>
  </div>

{% endblock settings-content %}

hyrodactil/templates/companysettings/information_form.html
{% extends "companysettings/main.html" %}
{% load i18n %}


{% block title %}
  {% trans 'Company information' %}
{% endblock title %}


{% block settings-content %}
  <form action="." method="POST" class="large-6 columns">
    {% csrf_token %}

    {% for field in form %}
      {% include 'core/_field.html' with field=field %}
    {% endfor %}

    <div class="large-12 columns">
     <input type="submit" value="{% trans 'Save' %}" class="button" />
    </div>

  </form>

{% endblock settings-content %}

hyrodactil/templates/companysettings/interviewstage_list.html
{% extends "companysettings/main.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}
  {% trans 'Stages' %}
{% endblock title %}


{% block settings-content %}
  <div class="large-6 columns">
    <div id="sort-table">
      <table>
        <thead>
        <tr>
          <th class="large-2 columns" colspan="2"></th>
          <th class="large-8 columns">{% trans "Name" %}</th>
          <th class="large-2 columns" colspan="2"></th>
        </tr>
        </thead>

        <tbody class="list">
          {% for stage in stages %}
            <tr>
              <td class="large-1 columns">
                <a href="#" class="edit">
                  {% if not forloop.last %}
                    <a href="{% url "companysettings:reorder_stage" stage.id 1 %}">
                      <i class="icon-arrow-down icon-2x"></i>
                    </a>
                  {% endif %}
                </a>
              </td>
              <td class="large-1 columns">
                <a href="#">
                  {% if not forloop.first %}
                    <a href="{% url "companysettings:reorder_stage" stage.id -1 %}">
                      <i class="icon-arrow-up icon-2x"></i>
                    </a>
                  {% endif %}
                </a>
              </td>
              <td class="id" style="display: none;">{{ stage.id }}</td>
              <td class="large-8 columns name">{{ stage.name }}</td>
              <td class="large-1 columns">
                <a href="#" class="edit"><i class="icon-edit icon-2x"></i></a>
              </td>
              <td class="large-1 columns">
                <a href="#" class="delete-link"><i class="icon-trash icon-2x"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <form action="." method="POST">
        <div class="large-10 columns">
          <input type="hidden" class="form-id" />
          <input type="text" class="form-name" placeholder="{% trans 'Name' %}" />
        </div>
        <div class="large-2 columns">
          <a class="button save" href="#">{% trans 'Save' %}</a>
        </div>
      </form>

    </div>

  </div>

  {% include "companysettings/_modal_confirm.html" %}

{% endblock settings-content %}

{% block extra-js %}
  <script src="{% static "js/vendor/list.min.js" %}"></script>
  <script src="{% static "js/csrf.js" %}"></script>
  <script src="{% static "js/CompanySettings.js" %}"></script>
  <script>
    $(document).ready(function() {
      Hizard.CompanySettings(
        "{% url 'companysettings:ajax_stage' %}",
        "{% url 'companysettings:delete_stage' 8888 %}",
        '{% url "companysettings:reorder_stage" 0 -1 %}',
        '{% url "companysettings:reorder_stage" 0 1 %}'
      );
    });
  </script>
{% endblock extra-js %}

hyrodactil/templates/companysettings/main.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load core_extra %}

{% block title %}
  {% trans 'Settings' %}
{% endblock title %}


{% block content %}
  <h1>{% trans "Settings" %}</h1>

  <ul class="inline-list settings-links">
    <li>
      <a class="{% active request 'companysettings:main' %}" href="{% url 'companysettings:main' %}">
        {% trans 'Users' %}
      </a>
    </li>
    <li>
      <a class="{% active request 'companysettings:list_stages' %}" href="{% url 'companysettings:list_stages' %}">
        {% trans 'Interview Stages' %}
      </a>
    </li>
    <li>
      <a class="{% active request 'companysettings:update_information' %}" href="{% url 'companysettings:update_information' %}">
        {% trans 'Company information' %}
      </a>
    </li>
    <li>
      <a class="{% active request 'customisable_emails:list' %}" href="{% url 'customisable_emails:list' %}">
        {% trans 'Emails' %}
      </a>
    </li>
    <li>
      <a class="{% active request 'companysettings:widget' %}" href="{% url 'companysettings:widget' %}">
        {% trans 'Widget' %}
      </a>
    </li>
  </ul>

  {% block settings-content %}
  {% endblock settings-content %}

{% endblock content %}

hyrodactil/templates/companysettings/widget.html
{% extends "companysettings/main.html" %}
{% load i18n %}


{% block title %}
  {% trans 'Opening widget' %}
{% endblock title %}


{% block settings-content %}
  {% trans 'Place the following snippet where you would like your openings to appear' %}

  <pre class="widget-snippet">
    {{ snippet }}
  </pre>

{% endblock settings-content %}