hyrodactil/accounts/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(
        r'^register/$',
        views.RegistrationView.as_view(),
        name='register'
    ),
    url(
        r'^confirmation/$',
        views.RegistrationConfirmationView.as_view(),
        name='register_confirmation'
    ),
    url(
        r'^activate/(?P<activation_key>\w+)/$',
        views.ActivateView.as_view(),
        name='activate'
    ),
    url(
        r'^promote/(?P<user_pk>\w+)/$',
        views.PromoteView.as_view(),
        name='promote'
    ),
    url(
        r'^delete/(?P<user_pk>\w+)/$',
        views.DeleteView.as_view(),
        name='delete'
    ),
    url(
        r'^details/$',
        views.ChangeDetailsView.as_view(),
        name='change_details'
    )
)

hyrodactil/applications/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
   url(
       r'^$',
       views.ApplicationListView.as_view(),
       name='list_applications'
   ),
   url(
       r'^list/(?P<pk>\d+)/$',
       views.ApplicationListView.as_view(),
       name='list_applications_opening'
   ),
   url(
        r'^(?P<pk>\d+)/$',
        views.ApplicationDetailView.as_view(),
        name='application_detail'
   ),
   url(
        r'^(?P<application_id>\d+)/create_message/$',
        views.ApplicationMessageCreateView.as_view(),
        name='create_message'
   ),
   url(
        r'^add/(?P<opening_id>\d+)/$',
        views.ManualApplicationView.as_view(),
        name='manual_application'
   ),
   url(
       r'^rate/(?P<application_id>\d+)/(?P<rating>-?\d+)$',
       views.RateView.as_view(),
       name='rate'
   )
)

hyrodactil/hyrodactil/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'',
        include(
            'accounts.auth_urls',
            namespace='auth',
            app_name='accounts'
        )
    ),
    url(
        r'^accounts/',
        include(
            'accounts.urls',
            namespace='accounts',
            app_name='accounts'
        )
    ),
    url(
        r'^companies/',
        include(
            'companies.urls',
            namespace='companies',
            app_name='companies'
        )
    ),
    url(
        r'^settings/',
        include(
            'companysettings.urls',
            namespace='companysettings',
            app_name='companysettings'
        )
    ),
    url(
        r'^openings/',
        include(
            'openings.urls',
            namespace='openings',
            app_name='openings')
    ),
    url(
        r'^applications/',
        include(
            'applications.urls',
            namespace='applications',
            app_name='applications')
    ),
    url(
        r'^emails/',
        include(
            'customisable_emails.urls',
            namespace='customisable_emails',
            app_name='customisable_emails'
        )
    ),
    url(
        r'^',
        include(
            'dashboard.urls',
            namespace='dashboard',
            app_name='dashboard')
    ),
    url(
        r'^',
        include(
            'public.urls',
            namespace='public',
            app_name='public')
    )

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

hyrodactil/applications/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel

from accounts.models import CustomUser
from companysettings.models import InterviewStage
from openings.models import Opening, OpeningQuestion


class Applicant(TimeStampedModel):
    first_name = models.CharField(max_length=770)
    last_name = models.CharField(max_length=770)
    # 254 is the max length of an email
    email = models.EmailField(max_length=254)
    resume = models.FileField(
        upload_to="tmp_resumes",
        help_text=_('PDF/doc files only')
    )

    ALLOWED_EXTENSIONS = ['.pdf', '.doc', '.docx']
    ALLOWED_CONTENT_TYPES = ['application/pdf',
        'application/msword',
        'application/vnd.oasis.opendocument.text']

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def __unicode__(self):
        return self.get_full_name()


class Application(TimeStampedModel):
    applicant = models.ForeignKey(Applicant)
    opening = models.ForeignKey(Opening)
    current_stage = models.ForeignKey(InterviewStage, null=True)

    def get_rating(self):
        ratings = ApplicationRating.objects.filter(
            application=self
        ).select_related('CustomUser')

        rating = 0

        for user_rating in ratings:
            rating += user_rating.rating

        return rating

    def save_rating(self, user, rating):
        int_rating = int(rating)

        if int_rating not in [-1, 0, 1]:
            return False

        rating_obj = ApplicationRating.objects.filter(
            application=self,
            user=user
        ).select_related('CustomUser')

        if rating_obj:
            rating_obj = rating_obj[0]
            if rating_obj.rating == int_rating:
                return True
            rating_obj.rating = int_rating
            rating_obj.save()
            return True

        ApplicationRating.objects.create(
            application=self,
            user=user,
            rating=int_rating
        ).save()

        return True

    def get_user_rating(self, user):
        rating_obj = ApplicationRating.objects.filter(
            application=self,
            user=user
        ).select_related('CustomUser')

        if rating_obj:
            return rating_obj[0].rating

        return 0

    def __unicode__(self):
        return self.applicant.get_full_name()


class ApplicationAnswer(TimeStampedModel):
    application = models.ForeignKey(Application, related_name='answers')
    question = models.ForeignKey(OpeningQuestion)

    answer = models.TextField(blank=True, null=True)

    def __str__(self):
        return 'Answer to: %s' % self.question.title

class ApplicationStageTransition(TimeStampedModel):
    application = models.ForeignKey(
        Application, related_name='stage_transitions'
    )
    user = models.ForeignKey(CustomUser, null=True)
    stage = models.ForeignKey(InterviewStage)

    class Meta:
        ordering = '-created',

    def __str__(self):
        return "%s %s %s" % (self.application, self.user, self.stage)


class ApplicationMessage(TimeStampedModel):
    application = models.ForeignKey(Application)
    user = models.ForeignKey(CustomUser)
    parent = models.ForeignKey('ApplicationMessage', null=True, blank=True)

    body = models.TextField()

    class Meta:
        ordering = ('-created',)


class ApplicationRating(TimeStampedModel):
    application = models.ForeignKey(Application)
    user = models.ForeignKey(CustomUser)
    rating = models.IntegerField(default=0)

hyrodactil/applications/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView, CreateView, TemplateView

from braces.views import LoginRequiredMixin

from .forms import ApplicationStageTransitionForm, ApplicationMessageForm
from .forms import ApplicationForm
from .models import Application, ApplicationMessage, Applicant
from .threaded_discussion import group
from companysettings.models import InterviewStage
from core.views import MessageMixin, RestrictedListView
from customisable_emails import send_customised_email
from openings.models import Opening


class ApplicationListView(LoginRequiredMixin, RestrictedListView):
    model = Application

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)
        context['stages'] = InterviewStage.objects.filter(
            company=self.request.user.company
        )

        opening_id = self.kwargs.get('pk', None)

        if opening_id:
            opening = get_object_or_404(Opening, id=opening_id)
            context['application_list'] = context['application_list'].filter(
                opening=opening
            )
            context['opening'] = opening

        return context

    def get_queryset(self):
        qs = Application.objects.filter(
            opening__company=self.request.user.company
        ).order_by('opening').select_related(
            'applicant', 'opening', 'current_stage'
        )
        return qs


class ApplicationMessageCreateView(LoginRequiredMixin, CreateView):
    model = ApplicationMessage
    form_class = ApplicationMessageForm
    action = 'created'

    def dispatch(self, request, application_id, **kwargs):
        self.application = get_object_or_404(
            Application,
            opening__company=self.request.user.company,
            pk=application_id
        )
        return super(ApplicationMessageCreateView, self).dispatch(
            request, application_id, **kwargs)

    def get_success_url(self):
        return reverse(
            'applications:application_detail',
            args=(self.application.id,)
        )

    def form_valid(self, form):
        new_message = form.save(commit=False)
        new_message.application = self.application
        new_message.user = self.request.user
        return super(ApplicationMessageCreateView, self).form_valid(form)


class ApplicationDetailView(LoginRequiredMixin, FormView):
    model = Application
    form_class = ApplicationStageTransitionForm
    template_name = 'applications/application_detail.html'

    def get_application(self):
        if not hasattr(self, "_application"):
            try:
                self._application = Application.objects.get(
                    pk=self.kwargs['pk'],
                    opening__company=self.request.user.company
                )
            except Application.DoesNotExist:
                raise Http404

        return self._application

    def get_form_kwargs(self):
        default_kwargs = super(ApplicationDetailView, self).get_form_kwargs()
        default_kwargs['company'] = self.request.user.company
        application = self.get_application()
        default_kwargs['initial'] = dict(stage=application.current_stage)
        return default_kwargs

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetailView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        application = self.get_application()
        context['application'] = application
        context['discussion'] = group(application.applicationmessage_set.all())
        context['new_message_form'] = ApplicationMessageForm()
        context['user_rating'] = application.get_user_rating(context['user'])
        context['rating'] = application.get_rating()
        context['answers'] = application.answers.all()
        return context

    def form_valid(self, form):
        application = self.get_application()
        transition = form.save(commit=False)
        transition.application = application
        transition.user = self.request.user
        transition.save()
        application.current_stage = transition.stage
        application.save()

        applicant = application.applicant
        opening = application.opening
        if transition.stage.tag == "REJECTED":
            send_customised_email("application_rejected",
                company=opening.company,
                to=applicant.email,
                context=dict(applicant_first_name=applicant.first_name,
                  applicant_last_name=applicant.last_name,
                  company=mark_safe(opening.company.name),
                  opening=mark_safe(opening.title))
            )
        elif transition.stage.tag == "HIRED":
            send_customised_email("candidate_hired",
                company=opening.company,
                to=applicant.email,
                context=dict(applicant_first_name=applicant.first_name,
                  applicant_last_name=applicant.last_name,
                  company=mark_safe(opening.company.name),
                  opening=mark_safe(opening.title))
            )
            messages.success(self.request, _('Applicant marked as hired.'))

        return redirect(
            'applications:application_detail',
            pk=self.kwargs['pk']
        )


class ManualApplicationView(LoginRequiredMixin, MessageMixin, FormView):
    model = Applicant
    form_class = ApplicationForm
    template_name = 'applications/manual_application.html'
    success_message = _('Application manually added.')

    def get_context_data(self, **kwargs):
        context = super(ManualApplicationView, self).get_context_data(**kwargs)
        context["opening"] = self.opening
        return context

    def get_form_kwargs(self):
        default_kwargs = super(ManualApplicationView, self).get_form_kwargs()
        self.opening = Opening.objects.get(
            pk=self.kwargs["opening_id"]
        )
        default_kwargs['opening'] = self.opening
        return default_kwargs

    def form_valid(self, form):
        self.success_url = reverse(
            'applications:list_applications_opening',
            args=[self.opening.id]
        )
        form.save()
        return super(ManualApplicationView, self).form_valid(form)


class RateView(LoginRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        application = get_object_or_404(
            Application.objects.select_related('opening', 'opening__company'),
            id=self.kwargs['application_id']
        )
        if application.opening.company != request.user.company:
            raise Http404

        result = application.save_rating(request.user, self.kwargs['rating'])
        if result:
            messages.success(request, _('Application rated.'))
        else:
            messages.error(request, _("Couldn't rate the application"))

        return redirect(
            reverse('applications:application_detail', args=(application.id,))
        )

hyrodactil/templates/applications/_comments.html
{% load i18n %}

<div>
  {% for level, message in discussion %}
    {% ifchanged level %}
      {% if not forloop.first %}
        {% ifchanged level %}
          </div>
        {% endifchanged %}
      {% endif %}

      <div class="message-level-{{ level }} message-thread">
    {% endifchanged %}

  <div class="message">
    <img src="{{ message.user.get_avatar_url }}" alt="{{ message.user.name }}" class="avatar" />
    <div class="message-content">
      <span class="name">{{ message.user.name }}</span>
      —
      <span class="time">{{ message.created|timesince }} {% trans 'ago' %}</span>
      <p>
        {{ message.body }}
      </p>
    </div>
    <a href="#" data-reply-to="{{ message.pk }}" class="reply-link">{% trans 'Reply' %}</a>
  </div>

  {% if forloop.last %}
    </div>
  {% endif %}
  {% endfor %}
</div>


<form action="{% url 'applications:create_message' application.id %}"
  method="POST"
  id="new-message-form">
  {% csrf_token %}

  <label for="{{ new_message_form.body.auto_id }}">{% trans 'Post a new message' %}</label>
   {{ new_message_form.body }}

  <div class="form-actions end">
    {{ new_message_form.parent }}
    <input type="submit" value="{% trans 'Save message' %}" class="button right post-message" />
  </div>
</form>

hyrodactil/templates/applications/_comments_tab.html
{% load i18n %}

<div>
  {% for level, message in discussion %}
    {% ifchanged level %}
      {% if not forloop.first %}
        {% ifchanged level %}
          </div>
        {% endifchanged %}
      {% endif %}

      <div class="message-level-{{ level }} message-thread">
    {% endifchanged %}

  <div class="message">
    {# only for test, users always have an avatar #}
    {% if message.user.avatar %}
      <img src="{{ message.user.avatar.url }}" alt="{{ message.user.name }}" class="left" />
    {% endif %}
    <div class="message-content">

      <span class="name">{{ message.user.name }}</span>
      —
      <span class="time">{{ message.created|timesince }} {% trans 'ago' %}</span>
      <p>
        {{ message.body }}
      </p>
      <a href="#" data-reply-to="{{ message.pk }}" class="reply-link">{% trans 'Reply' %}</a>
    </div>

  </div>

  {% if forloop.last %}
    </div>
  {% endif %}
  {% endfor %}
</div>


<form action="{% url 'applications:create_message' application.id %}"
  method="POST"
  id="new-message-form">
  {% csrf_token %}
    <div>
      {{ new_message_form.body }}
    </div>

  <div>
    <div class="form-actions end">
      <div>
        {{ new_message_form.parent }}
        <input type="submit" value="{% trans 'Save message' %}" class="button-positive right" />
      </div>
      <div class="clear"></div>
    </div>
  </div>
</form>

hyrodactil/templates/applications/_discussion_tab.html
{% load i18n %}

<div>
  {% for level, message in discussion %}
    {% ifchanged level %}
      {% if not forloop.first %}
        {% ifchanged level %}
          </div>
        {% endifchanged %}
      {% endif %}

      <div class="message-level-{{ level }} message-thread">
    {% endifchanged %}

  <div class="message">
    {# only for test, users always have an avatar #}
    {% if message.user.avatar %}
      <img src="{{ message.user.avatar.url }}" alt="{{ message.user.name }}" class="left" />
    {% endif %}
    <div class="message-content">

      <span class="name">{{ message.user.name }}</span>
      —
      <span class="time">{{ message.created|timesince }} {% trans 'ago' %}</span>
      <p>
        {{ message.body }}
      </p>
      <a href="#" data-reply-to="{{ message.pk }}" class="reply-link">{% trans 'Reply' %}</a>
    </div>

  </div>

  {% if forloop.last %}
    </div>
  {% endif %}
  {% endfor %}
</div>


<form action="{% url 'applications:create_message' application.id %}"
  method="POST"
  id="new-message-form">
  {% csrf_token %}
    <div>
      {{ new_message_form.body }}
    </div>

  <div>
    <div class="form-actions end">
      <div>
        {{ new_message_form.parent }}
        <input type="submit" value="{% trans 'Save message' %}" class="button-positive right" />
      </div>
      <div class="clear"></div>
    </div>
  </div>
</form>

hyrodactil/templates/applications/_kanban.html
{% extends "base.html" %}

{% load i18n %}
{% load core_extra %}
{% load staticfiles %}

{% block content %}
<div class="kanban-board">
  {% for stage in board %}
    <div class="kanban-list">
      <div class="kanban-list-header"><h2>{{ stage.name }}</h2></div>
      <div class="kanban-list-cards" data-stage-id="{{ stage.id }}">
        {% for application in board|get_item:stage %}

          <div class="kanban-card" data-id="{{ application.id }}" data-position="{{ application.position }}">
            <span>{{ application.applicant.first_name }} {{ application.applicant.last_name }}</span>
            <br>
            <span>
              <a href="{% url 'openings:update_opening' application.opening.id %}">{{ application.opening.title }}</a>
            </span>
          </div>

        {% endfor %}
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

{% block extra-js %}
  <script src="{% static "js/vendor/jquery.ui.js" %}"></script>
  <script src="{% static "js/kanban.js" %}"></script>
  <script src="{% static "js/csrf.js" %}"></script>
  <script>
    $(function () {
      $('.kanban-board').kanban({
        others: {
          updatePositionsURL: "{% url 'applications:update_positions' %}"
        }
      });
    });
  </script>
{% endblock extra-js %}

hyrodactil/templates/applications/application_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {{ application.applicant.first_name }} {{ application.applicant.last_name }}
{% endblock title %}

{% block content %}

  <h1>
    {{ application.applicant.first_name }} {{ application.applicant.last_name }}
    <small>{% trans 'applying for ' %}<a href="{% url 'openings:detail_opening' application.opening.id %}">{{ application.opening.title }}</a></small>
  </h1>



  <div class="large-8 columns">

    <div>
      <span class="application-rating">
        {% if user_rating != -1 %}
          <a href="{% url 'applications:rate' application.id -1 %}"><i class="icon-thumbs-down"></i></a>
        {% else %}
          <a href="{% url 'applications:rate' application.id 0 %}" class="rate-neutral"><i class="icon-thumbs-down"></i></a>
        {% endif %}

        {{ rating }}

        {% if user_rating != 1 %}
          <a href="{% url 'applications:rate' application.id 1 %}"><i class="icon-thumbs-up"></i></a>
        {% else %}
          <a href="{% url 'applications:rate' application.id 0 %}" class="rate-neutral"><i class="icon-thumbs-up"></i></a>
        {% endif %}
       </span>
    </div>

    <h2>{% trans 'Informations' %}</h2>
    <i class="icon-envelope"></i> {{ application.applicant.email }}
    <br>
    <br>
    <a href="http://docs.google.com/gview?url={{ application.applicant.resume.url }}" target="_blank"class="button">{% trans 'See resume' %}</a>
    <a href="{{ application.applicant.resume.url }}" target="_blank" class="button">{% trans 'Download resume' %}</a>

    {% if answers %}
      <h4>{% trans 'Answers' %}</h4>
      {% for answer in answers %}
        <p>
          <strong>{{ answer.question.title }}</strong><br>
          {{ answer.answer }}
        </p>
      {% endfor %}
    {% endif %}

    <h2>{% trans 'Discussion' %}</h2>
    {% include 'applications/_comments.html' with application=application new_message_form=new_message_form discussion=discussion %}
  </div>

  <div class="large-4 columns">
    <div>
      <form action="." method="POST" id="transition-form">
        {% csrf_token %}

        {% if form.errors %}
          <span class="has-errors"></span>
        {% endif %}

        {{ form.stage.label_tag }}
        {{ form.stage }}
      </form>
    </div>
    <h2>{% trans 'Event feed' %}</h2>

    {% for transition in application.stage_transitions.all %}
      <div>
        <span>{{ transition.created|date:"Y/m/d" }} - {% trans 'Moved to ' %}{{ transition.stage }}</span>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

{% block extra-js %}
  <script type="text/javascript">
    $("a.reply-link").click(function(event) {
      event.preventDefault();

      var newForm = $("#new-message-form").clone(),
              link = $(this),
              parentMessage = link.data("reply-to");
      link.after(newForm);
      newForm.find("#id_parent").val(parentMessage);
      newForm.find('label').remove();
      newForm.find('.post-message').val('{% trans 'Reply' %}');
      $(this).remove();
    });

    $("select#id_stage").change(function () {
      $("form#transition-form").submit();
    });
  </script>
{% endblock extra-js %}

hyrodactil/templates/applications/application_list.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}


{% block title %}
  {% if opening %}
    {% trans 'Applications for ' %} {{ opening.title }}
  {% else %}
    {% trans 'Applications' %}
  {% endif %}
{% endblock title %}

{% block content %}

  <h1>
    {% if opening %}
      {% trans 'Applications for ' %} {{ opening.title }}
    {% else %}
      {% trans 'All applications' %}
    {% endif %}
  </h1>

  <div>

    <div id="table-applicants">

      <div class="large-2 columns">
        <input type="search" class="search" placeholder="Search" />

        {% for stage in stages %}
          <label>
            <input class="filter-stages" type="checkbox" value="{{ stage.name }}"/>   {{ stage.name }}
          </label>
        {% endfor %}

      </div>

      <div class="large-10 columns">

        <table>

          <thead>
            <tr class="row">
              <th class="large-3 columns sort" data-sort="name"><i class="icon-sort"></i> {% trans "Name" %}</th>
              <th class="large-2 columns sort" data-sort="applied"><i class="icon-sort"></i> {% trans "Applied" %}</th>
              <th class="large-2 columns sort" data-sort="stage"><i class="icon-sort"></i> {% trans "Stage" %}</th>
              <th class="large-3 columns sort" data-sort="opening"><i class="icon-sort"></i> {% trans "Opening" %}</th>
              <th class="large-2 columns sort" data-sort="rating"><i class="icon-sort"></i> {% trans "Rating" %}</th>
            </tr>
          </thead>

          <tbody class="list">
            {% for application in application_list %}
              <tr class="row">
                <td class="id" style="display: none;">{{ application.id }}</td>
                <td class="large-3 columns name">
                  <a href="{% url 'applications:application_detail' application.id %}">
                    {{ application.applicant.get_full_name }}
                  </a>
                </td>
                <td class="large-2 columns applied">{{ application.created|date:"Y/m/d"  }}</td>
                <td class="large-2 columns stage">{{ application.current_stage }}</td>
                <td class="large-3 columns opening">
                  <a href="{% url 'openings:detail_opening' application.opening.id %}">
                    {{ application.opening.title }}
                  </a>
                </td>
                <td class="large-2 columns rating">{{ application.get_rating }}</td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>

  </div>

{% endblock content %}

{% block extra-js %}
  <script src="{% static "js/vendor/list.min.js" %}"></script>

  <script>
    var options = {
      valueNames: ['id', 'name', 'applied', 'stage', 'opening', 'rating']
    };
    var applicantTable = new List('table-applicants', options);

    var $filterStages = $('.filter-stages');

    $filterStages.click(function() {
      var selectedFilterStage = $('.filter-stages:checkbox:checked').map(function() {
        return this.value;
      }).get();

      applicantTable.filter(function(item) {
        if (selectedFilterStage.length === 0) {
          return true;
        }
        return $.inArray(item.values().stage, selectedFilterStage) !== -1;
      });
    });

  </script>
{% endblock %}

hyrodactil/templates/applications/apply.html
{% extends "base_openings.html" %}

{% load i18n %}


{% block title %}
   {{ opening.title }} - {{ opening.company.name }}
{% endblock title %}


{% block header %}
    {{ opening.company.name }}
{% endblock header %}


{% block apply-header %}
    <div class="apply-header">
        <h3>{{ opening.title }}</h3>
        <a href="{% url 'applications:list_openings' opening.company.id %}">{% trans 'Back to the job listing' %}</a>
    </div>
{% endblock apply-header %}


{% block section %}
    {{ opening.description }}
{% endblock section %}


{% block aside %}
  <form action="." method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in form %}
        {{ field.label_tag }}
        {{ field }}
    {% endfor %}
    <br><br><br>
    <input type="submit" value="Submit" class="button">
  </form>
{% endblock aside %}

hyrodactil/templates/applications/manual_application.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {% trans 'Manual application' %}
{% endblock title %}


{% block content %}
  <h1>{% trans 'Add applicant for ' %}{{ opening.title }}</h1>

  <form class="large-6 columns" action="." method="POST" enctype="multipart/form-data" id="action-form">
    {% csrf_token %}

    {% if form.non_field_errors %}
      <small class="error">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </small>
    {% endif %}

    {% for field in form %}
      {% include 'core/_field.html' with field=field %}
    {% endfor %}

    <div class="row">
      <div class="large-12 columns text-right">
        <input type="submit" class="button" value="{% trans 'Save' %}" />
      </div>
    </div>
  </form>
{% endblock content %}

hyrodactil/templates/applications/opening_list.html
{% extends "base_openings.html" %}

{% load i18n %}


{% block title %}
  {{ company.name }} - {% trans 'Job Board' %}
{% endblock title %}

{% block header %}
  {{ company.name }}
{% endblock header %}

{% block section %}
  <h3>{% trans 'Openings' %}</h3>

  {% for opening in openings %}
    <div class="opening">
      <a href="{% url 'applications:apply' opening.id %}">{{ opening.title }}</a>
      <br>
      {% if opening.department %}
        <span>Department: {{ opening.department }}</span>
      {% endif %}
    </div>
  {% endfor %}
{% endblock section %}


{% block aside %}
  Add company description field to the company model
{% endblock aside %}